### ISSUE TITLE
Syntax error with `<<` and `>>>` operators

### ISSUE THREAD

**Issue by NabiKAZ** [sstur/js2php#7]
js:
```
b = 0x1ffff << 15 | 11 >>> 17;
```
php: (line 2537)
```
$b = to_number((131071.0 << 15.0)) | to_number((11.0 >>> 17.0));
```
error:
```
Parse error: syntax error, unexpected '>' in example.php on line 2537
```

**Comment by sstur** [comment]
I'm guessing it's the `>>>` operator that PHP doesn't support. It will need to be converted to a function call.

I'm not currently maintaining this project, but if anyone wants to make a PR for this, you'll need to add one transform to `x >>> y` to `zero_fill_right_shift(x, y)` and then you'll need to add `zero_fill_right_shift()` to the PHP runtime. See [here](https://stackoverflow.com/a/27263298/481565).
